import img_0 from './images/img_0.png';
import img_1 from './images/img_1.png';
import img_2 from './images/img_2.png';
import img_3 from './images/img_3.png';
import img_4 from './images/img_4.png';
import img_5 from './images/img_5.png';
import img_6 from './images/img_6.png';
import img_7 from './images/img_7.png';
import img_8 from './images/img_8.png';
import img_9 from './images/img_9.png';

export default {
  v: '5.9.0',
  fr: 30,
  ip: 0,
  op: 601,
  w: 9284,
  h: 9402,
  nm: '02 - Rinpoche',
  ddd: 0,
  assets: [
    { id: 'image_0', w: 2957, h: 1778, u: '', p: img_0, e: 0 },
    { id: 'image_1', w: 2367, h: 1973, u: '', p: img_1, e: 0 },
    { id: 'image_2', w: 4988, h: 8864, u: '', p: img_2, e: 0 },
    { id: 'image_3', w: 6493, h: 9402, u: '', p: img_3, e: 0 },
    { id: 'image_4', w: 6493, h: 9402, u: '', p: img_4, e: 0 },
    { id: 'image_5', w: 5583, h: 6427, u: '', p: img_5, e: 0 },
    { id: 'image_6', w: 659, h: 1742, u: '', p: img_6, e: 0 },
    { id: 'image_7', w: 6493, h: 9402, u: '', p: img_7, e: 0 },
    { id: 'image_8', w: 6493, h: 9402, u: '', p: img_8, e: 0 },
    { id: 'image_9', w: 6493, h: 9402, u: '', p: img_9, e: 0 },
    {
      id: 'comp_0',
      nm: '02 - Rinpoche 2',
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 2,
          nm: 'R cloth',
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [6301, 4494, 0], ix: 2, l: 2 },
            a: { a: 0, k: [1478.5, 889, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ef: [
            {
              ty: 34,
              nm: 'Puppet',
              np: 6,
              mn: 'ADBE FreePin3',
              ix: 1,
              en: 1,
              ef: [
                { ty: 7, nm: 'Puppet Engine', mn: 'ADBE FreePin3 Puppet Engine', ix: 1, v: { a: 0, k: 2, ix: 1 } },
                { ty: 0, nm: 'Mesh Rotation Refinement', mn: 'ADBE FreePin3 Auto Rotate Pins', ix: 2, v: { a: 0, k: 20, ix: 2 } },
                { ty: 7, nm: 'On Transparent', mn: 'ADBE FreePin3 On Transparent', ix: 3, v: { a: 0, k: 0, ix: 3 } },
                {
                  ty: '',
                  nm: 'arap',
                  np: 3,
                  mn: 'ADBE FreePin3 ARAP Group',
                  ix: 4,
                  en: 1,
                  ef: [
                    { ty: 6, nm: 'Auto-traced Shapes', mn: 'ADBE FreePin3 Outlines', ix: 1, v: 0 },
                    {
                      ty: '',
                      nm: 'Mesh',
                      np: 2,
                      mn: 'ADBE FreePin3 Mesh Group',
                      ix: 2,
                      en: 1,
                      ef: [
                        {
                          ty: '',
                          nm: 'Mesh 1',
                          np: 8,
                          mn: 'ADBE FreePin3 Mesh Atom',
                          ix: 1,
                          en: 1,
                          ef: [
                            { ty: 6, nm: 'Mesh', mn: 'ADBE FreePin3 Mesh', ix: 1, v: 0 },
                            { ty: 0, nm: 'Triangles', mn: 'ADBE FreePin3 Mesh Tri Count', ix: 2, v: { a: 0, k: 50, ix: 2 } },
                            { ty: 0, nm: 'Density', mn: 'ADBE FreePin3 Mesh Tri Density', ix: 3, v: { a: 0, k: 10, ix: 3 } },
                            { ty: 0, nm: 'Expansion', mn: 'ADBE FreePin3 Mesh Expansion', ix: 4, v: { a: 0, k: 3, ix: 4 } },
                            {
                              ty: '',
                              nm: 'Deform',
                              np: 8,
                              mn: 'ADBE FreePin3 PosPins',
                              ix: 5,
                              en: 1,
                              ef: [
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 7',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 1,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 201, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: { a: 0, k: [1014, 871], ix: 4 },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 6',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 2,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 202, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: { a: 0, k: [486, 931], ix: 4 },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 5',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 3,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 203, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: { a: 0, k: [1254, 1723], ix: 4 },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 4',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 4,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 204, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 0,
                                            s: [2838, 1495],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 47,
                                            s: [2802, 1519],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 108,
                                            s: [2856, 1417],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 150, s: [2838, 1495] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 3',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 5,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 205, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 0,
                                            s: [2754, 451],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 40,
                                            s: [2778, 409],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 97,
                                            s: [2754, 499],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 150, s: [2754, 451] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 2',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 6,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 206, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 0,
                                            s: [1494, 667],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.873 },
                                            o: { x: 0.333, y: 0 },
                                            t: 23,
                                            s: [1512, 649],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0.283 },
                                            t: 74,
                                            s: [1506.538, 696.462],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 150, s: [1494, 667] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 1',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 7,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 207, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 0,
                                            s: [153, 1420],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 57,
                                            s: [150, 1408],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 119,
                                            s: [153, 1420],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 150, s: [153, 1420] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                              ],
                            },
                            { ty: '', nm: 'Overlap', np: 1, mn: 'ADBE FreePin3 HghtPins', ix: 6, en: 1, ef: [] },
                            { ty: '', nm: 'Stiffness', np: 1, mn: 'ADBE FreePin3 StarchPins', ix: 7, en: 1, ef: [] },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 0,
          nm: 'Man',
          refId: 'comp_1',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4642, 4701, 0], ix: 2, l: 2 },
            a: { a: 0, k: [4049.5, 4701, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          tm: {
            a: 1,
            k: [
              { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [0] },
              { t: 300, s: [10] },
            ],
            ix: 2,
            x: "var $bm_rt;\n$bm_rt = loopOut('cycle', 0);",
          },
          w: 8099,
          h: 9402,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 2,
          nm: 'Tri',
          refId: 'image_4',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 76, s: [8] },
                { t: 150, s: [0] },
              ],
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 0, s: [5458.295, 3134.679, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 76, s: [5482.295, 3146.679, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 150, s: [5458.295, 3134.679, 0] },
              ],
              ix: 2,
              l: 2,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            a: { a: 0, k: [4350.5, 2793, 0], ix: 1, l: 2, x: 'var $bm_rt;\n$bm_rt = transform.anchorPoint;' },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 3,
          nm: 'Null 1',
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4726, 897, 0], ix: 2, l: 2 },
            a: { a: 0, k: [-1596, -2424, 0], ix: 1, l: 2 },
            s: { a: 0, k: [130, 130, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 5,
          ty: 2,
          nm: 'Ribbon L',
          parent: 4,
          refId: 'image_5',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 73, s: [17] },
                { t: 150, s: [0] },
              ],
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.667, y: 0.667 },
                  o: { x: 0.333, y: 0.333 },
                  t: 0,
                  s: [-1733.5, -2461.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 0.667 },
                  o: { x: 0.333, y: 0.333 },
                  t: 73,
                  s: [-1733.5, -2461.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 150, s: [-1733.5, -2461.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [2467.5, 1057.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [1, 2],
                    [1, 1],
                    [6.5, 11.5],
                    [-6.5, 13],
                    [-2, 3],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [6.5, -9],
                    [-19.5, 0],
                    [-6.5, -11.5],
                    [6.5, -13],
                    [-9, -21],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  v: [
                    [2427, 412],
                    [2017, 554],
                    [1913, 922],
                    [2109, 1298],
                    [2409.5, 1157.5],
                    [2448, 1150],
                    [2491, 1126.5],
                    [2451, 1092],
                    [2463, 1063],
                    [2503, 1049],
                    [2523, 995],
                    [2462, 960],
                    [2482, 882],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 6,
          ty: 2,
          nm: 'Ribbon R',
          parent: 4,
          refId: 'image_5',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 73, s: [-42] },
                { t: 150, s: [0] },
              ],
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            p: {
              a: 1,
              k: [
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 0,
                  s: [-1513.654, -2455.192, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0 },
                  t: 73,
                  s: [-1513.654, -2431.192, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 150, s: [-1513.654, -2455.192, 0] },
              ],
              ix: 2,
              l: 2,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            a: { a: 0, k: [2829.5, 1037.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [12, -25.5],
                    [1, 0],
                    [0, 0],
                    [-0.5, -0.5],
                    [-1.5, 0],
                    [-3, -0.5],
                    [2, -15],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [-12, 25.5],
                    [-10.5, 8.5],
                    [0, 0],
                    [53, 8],
                    [17, 4],
                    [3, 0.5],
                    [-2, 15],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  v: [
                    [2835, 836],
                    [2796.5, 978.5],
                    [2768, 992.5],
                    [2735, 998],
                    [2766, 1001],
                    [2828.5, 1040.5],
                    [2856, 1053.5],
                    [2861, 1103],
                    [2824, 1131],
                    [2844.5, 1151],
                    [2989, 1250],
                    [3205, 1326],
                    [3473, 1170],
                    [3717, 750],
                    [3365, 454],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 7,
          ty: 2,
          nm: 'L cloth',
          refId: 'image_6',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 75, s: [12] },
                { t: 150, s: [0] },
              ],
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            p: { a: 0, k: [2124, 5474, 0], ix: 2, l: 2 },
            a: { a: 0, k: [503.5, 391, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 8,
          ty: 2,
          nm: 'Layer 1 copy',
          refId: 'image_7',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4642, 4701, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3246.5, 4701, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 10,
          ty: 2,
          nm: 'Green',
          refId: 'image_8',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [0] },
                { t: 600, s: [360] },
              ],
              ix: 10,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            p: { a: 0, k: [4750, 1701, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3354.5, 1701, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100.992, 100.992, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 11,
          ty: 2,
          nm: 'Generative Fill 4/Eka_003.psd',
          cl: 'psd',
          refId: 'image_9',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4642, 4701, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3246.5, 4701, 0], ix: 1, l: 2 },
            s: {
              a: 1,
              k: [
                {
                  i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                  o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                  t: 0,
                  s: [100, 100, 100],
                },
                {
                  i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] },
                  o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] },
                  t: 30,
                  s: [98, 98, 100],
                },
                { t: 60, s: [100, 100, 100] },
              ],
              ix: 6,
              l: 2,
            },
          },
          ao: 0,
          ip: 0,
          op: 601,
          st: 0,
          bm: 0,
        },
      ],
    },
    {
      id: 'comp_1',
      nm: 'Man',
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 2,
          nm: 'Generative Fill',
          refId: 'image_1',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4994.5, 4385.5, 0], ix: 2, l: 2 },
            a: { a: 0, k: [1183.5, 986.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 2,
          nm: 'L Eye 2',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 16, s: [5] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 30, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 308, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 324, s: [5] },
                { t: 338, s: [0] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 0, s: [4217.75, 2052.25, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 16, s: [4217.25, 2073.25, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                {
                  i: { x: 0.667, y: 0.667 },
                  o: { x: 0.333, y: 0.333 },
                  t: 30,
                  s: [4217.75, 2052.25, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 308, s: [4217.75, 2052.25, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 324, s: [4217.25, 2073.25, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 338, s: [4217.75, 2052.25, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [3013.75, 1853.25, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [17.993, -5],
                    [6.001, -5.5],
                    [2.501, -5],
                    [4.501, -8.5],
                    [1, -4],
                    [-9.5, 6.5],
                    [-6.5, 0.5],
                    [-21, -4],
                    [-13.499, 8],
                    [-24.5, -10],
                    [-6, 7.5],
                    [-2.006, 23],
                    [0, 0],
                    [11.766, 11.322],
                    [20.5, 3.5],
                  ],
                  o: [
                    [-17.999, 5],
                    [-6.001, 5.5],
                    [-2.501, 5],
                    [-4.501, 8.5],
                    [-1, 4],
                    [9.5, -6.5],
                    [6.5, -0.5],
                    [21, 4],
                    [13.496, -8],
                    [24.5, 10],
                    [6, -7.5],
                    [2.006, -23],
                    [0, 0],
                    [-9.693, -9.328],
                    [-20.499, -3.5],
                  ],
                  v: [
                    [3017.502, 1780],
                    [2979.503, 1796.5],
                    [2947.002, 1819.5],
                    [2915.501, 1856.5],
                    [2910, 1880.5],
                    [2904, 1925],
                    [2923.5, 1908],
                    [2962.5, 1908],
                    [3025.999, 1894.5],
                    [3065.495, 1886],
                    [3118.995, 1895],
                    [3130.994, 1865],
                    [3114.816, 1831.379],
                    [3088.563, 1807.501],
                    [3052.494, 1788],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 2,
          nm: 'L Eye',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 43, ix: 10 },
            p: { a: 0, k: [4262.75, 2058.75, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3013.75, 1853.25, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [17.993, -5],
                    [6.001, -5.5],
                    [2.501, -5],
                    [4.501, -8.5],
                    [1, -4],
                    [-9.5, 6.5],
                    [-6.5, 0.5],
                    [-21, -4],
                    [-13.793, -7.481],
                    [25.583, 11.689],
                  ],
                  o: [
                    [-17.999, 5],
                    [-6.001, 5.5],
                    [-2.501, 5],
                    [-4.501, 8.5],
                    [-1, 4],
                    [9.5, -6.5],
                    [6.5, -0.5],
                    [21, 4],
                    [26.392, 14.314],
                    [-18.914, -8.642],
                  ],
                  v: [
                    [3009.254, 1798.614],
                    [2979.105, 1804.006],
                    [2950.062, 1823.959],
                    [2938.363, 1846.187],
                    [2944.776, 1857.023],
                    [2949.93, 1870.474],
                    [2962.142, 1867.081],
                    [3006.083, 1841.361],
                    [3046.144, 1842.193],
                    [3047.934, 1799.292],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 2,
          nm: 'L Eye LOWER',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 16, s: [-1] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 30, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 308, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 324, s: [-1] },
                { t: 338, s: [0] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 0, s: [4208.25, 2175.5, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 16, s: [4208.25, 2155.5, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                {
                  i: { x: 0.667, y: 0.667 },
                  o: { x: 0.333, y: 0.333 },
                  t: 30,
                  s: [4208.25, 2175.5, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 308, s: [4208.25, 2175.5, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 324, s: [4208.25, 2155.5, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 338, s: [4208.25, 2175.5, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [3004.25, 1976.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [4, -1],
                    [4.5, -4],
                    [0, 0],
                    [12.5, -6],
                    [10, -0.5],
                    [0, 0],
                    [8.501, -4],
                    [-1.5, -3.5],
                    [-36.501, -19.5],
                    [-63, 38.5],
                    [2, 29.5],
                    [0, 0],
                  ],
                  o: [
                    [-4, 1],
                    [-4.5, 4],
                    [0, 0],
                    [-12.5, 6],
                    [-10, 0.5],
                    [0, 0],
                    [-8.501, 4],
                    [1.5, 3.5],
                    [36.501, 19.5],
                    [63, -38.5],
                    [-2, -29.5],
                    [0, 0],
                  ],
                  v: [
                    [3080.5, 1892.5],
                    [3053.501, 1907.5],
                    [3038, 1917],
                    [3000, 1935],
                    [2978, 1938],
                    [2947, 1930.5],
                    [2905, 1922.5],
                    [2895.999, 1937.5],
                    [2904.999, 2011.5],
                    [3046.5, 2023],
                    [3138, 1939],
                    [3114, 1901.5],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 5,
          ty: 2,
          nm: 'R eye',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: {
              a: 1,
              k: [
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 0, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 16, s: [-3] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 30, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 308, s: [0] },
                { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 324, s: [-3] },
                { t: 338, s: [0] },
              ],
              ix: 10,
            },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 0, s: [3762, 2013, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 16, s: [3755, 2029, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 0.667 }, o: { x: 0.333, y: 0.333 }, t: 30, s: [3762, 2013, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 308, s: [3762, 2013, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 324, s: [3755, 2029, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 338, s: [3762, 2013, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [2555, 1811.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [33.315, 3.887],
                    [42, -21.5],
                    [0, 0],
                    [0, 0],
                    [-5, -1],
                    [-9, -5],
                    [-20, -14],
                    [-17, -6],
                    [-7, -1],
                    [-1, 23],
                    [-1, 50],
                    [22.001, 14],
                  ],
                  o: [
                    [-30, -3.5],
                    [-42, 21.5],
                    [0, 0],
                    [0, 0],
                    [5, 1],
                    [9, 5],
                    [20, 14],
                    [17, 6],
                    [7, 1],
                    [1, -23],
                    [1, -50],
                    [-22.001, -14],
                  ],
                  v: [
                    [2569, 1716],
                    [2472.089, 1740.701],
                    [2435, 1786],
                    [2467, 1790],
                    [2485, 1802],
                    [2514, 1799],
                    [2554, 1820],
                    [2617, 1843],
                    [2657, 1898],
                    [2674, 1890],
                    [2671, 1842],
                    [2643, 1753],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 6,
          ty: 2,
          nm: 'R eye 2',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: -3, ix: 10 },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 0, s: [3760, 2014, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 16, s: [3764, 1984, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 0.667 }, o: { x: 0.333, y: 0.333 }, t: 30, s: [3760, 2014, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 308, s: [3760, 2014, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0 }, t: 324, s: [3764, 1984, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 338, s: [3760, 2014, 0] },
              ],
              ix: 2,
              l: 2,
            },
            a: { a: 0, k: [2555, 1811.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [22.546, -9.834],
                    [0, 0],
                    [-77.219, 39.64],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  o: [
                    [-22.546, 9.834],
                    [-17.177, 10.73],
                    [77.219, -39.64],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                    [0, 0],
                  ],
                  v: [
                    [2467.801, 1793.912],
                    [2467.766, 1871.016],
                    [2614.472, 1937.786],
                    [2675.694, 1896.934],
                    [2651.618, 1878.649],
                    [2593.907, 1871.619],
                    [2543.287, 1843.932],
                    [2507.642, 1798.003],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 7,
          ty: 2,
          nm: 'Layer 2',
          refId: 'image_2',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [3698, 4631, 0], ix: 2, l: 2 },
            a: { a: 0, k: [2494, 4432, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 8,
          ty: 2,
          nm: 'Man body/Eka_003.psd',
          cl: 'psd',
          refId: 'image_3',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [4049.5, 4701, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3246.5, 4701, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 600,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 0,
      nm: '02 - Rinpoche 2',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [4642, 4701, 0], ix: 2, l: 2 },
        a: { a: 0, k: [4642, 4701, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 9284,
      h: 9402,
      ip: 0,
      op: 601,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 0,
      nm: '02 - Rinpoche 2',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [4642, 4701, 0], ix: 2, l: 2 },
        a: { a: 0, k: [4642, 4701, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ef: [
        {
          ty: 21,
          nm: 'Fill',
          np: 9,
          mn: 'ADBE Fill',
          ix: 1,
          en: 1,
          ef: [
            { ty: 10, nm: 'Fill Mask', mn: 'ADBE Fill-0001', ix: 1, v: { a: 0, k: 0, ix: 1 } },
            { ty: 7, nm: 'All Masks', mn: 'ADBE Fill-0007', ix: 2, v: { a: 0, k: 0, ix: 2 } },
            { ty: 2, nm: 'Color', mn: 'ADBE Fill-0002', ix: 3, v: { a: 0, k: [1, 1, 1, 1], ix: 3 } },
            { ty: 7, nm: 'Invert', mn: 'ADBE Fill-0006', ix: 4, v: { a: 0, k: 0, ix: 4 } },
            { ty: 0, nm: 'Horizontal Feather', mn: 'ADBE Fill-0003', ix: 5, v: { a: 0, k: 0, ix: 5 } },
            { ty: 0, nm: 'Vertical Feather', mn: 'ADBE Fill-0004', ix: 6, v: { a: 0, k: 0, ix: 6 } },
            { ty: 0, nm: 'Opacity', mn: 'ADBE Fill-0005', ix: 7, v: { a: 0, k: 1, ix: 7 } },
          ],
        },
        {
          ty: 5,
          nm: 'Simple Choker',
          np: 4,
          mn: 'ADBE Simple Choker',
          ix: 2,
          en: 1,
          ef: [
            { ty: 7, nm: 'View', mn: 'ADBE Simple Choker-0001', ix: 1, v: { a: 0, k: 1, ix: 1 } },
            {
              ty: 0,
              nm: 'Choke Matte',
              mn: 'ADBE Simple Choker-0002',
              ix: 2,
              v: {
                a: 1,
                k: [
                  { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 104, s: [-20] },
                  { i: { x: [0.667], y: [1] }, o: { x: [0.333], y: [0] }, t: 134, s: [-100] },
                  { t: 164, s: [-20] },
                ],
                ix: 2,
                x: "var $bm_rt;\n$bm_rt = loopOut('cycle', 0);",
              },
            },
          ],
        },
      ],
      w: 9284,
      h: 9402,
      ip: 0,
      op: 601,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
