import img_0 from './images/img_0.png';
import img_1 from './images/img_1.png';
import img_2 from './images/img_2.png';

export default {
  v: '5.9.0',
  fr: 30,
  ip: 0,
  op: 901,
  w: 6483,
  h: 9415,
  nm: 'Eka_005',
  ddd: 0,
  assets: [
    { id: 'image_0', w: 6273, h: 6777, u: '', p: img_0, e: 0 },
    { id: 'image_1', w: 3241, h: 3271, u: '', p: img_1, e: 0 },
    { id: 'image_2', w: 5510, h: 3920, u: '', p: img_2, e: 0 },
    {
      id: 'comp_0',
      nm: 'Man  Comp 1',
      fr: 30,
      layers: [
        {
          ddd: 0,
          ind: 1,
          ty: 3,
          nm: 'Null 2',
          sr: 1,
          ks: {
            o: { a: 0, k: 0, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [2796, 1676, 0], ix: 2, l: 2 },
            a: { a: 0, k: [-28, -1918, 0], ix: 1, l: 2 },
            s: { a: 0, k: [-102, 102, 100], ix: 6, l: 2 },
          },
          ao: 0,
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 2,
          ty: 2,
          nm: 'R Eye 2',
          parent: 1,
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 0.667 }, o: { x: 0.333, y: 0.333 }, t: 0, s: [0, 0, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 0.912 }, o: { x: 0.333, y: 0 }, t: 119, s: [0, 0, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 1 }, o: { x: 0.333, y: 0.098 }, t: 137, s: [0, 43.583, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 0.667 }, o: { x: 0.333, y: 0.333 }, t: 157, s: [0, 0, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { t: 300, s: [0, 0, 0] },
              ],
              ix: 2,
              l: 2,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            a: { a: 0, k: [3136.5, 3388.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [30, -4.484],
                    [26, -12.5],
                    [19.5, -16.318],
                    [3, -14],
                    [-4, -3],
                    [-5, 11],
                    [-7.5, -1],
                    [-20, 4.5],
                    [-4.5, 1],
                    [-13, -2],
                    [0, 0],
                    [2, 3],
                    [33.5, 10.516],
                  ],
                  o: [
                    [-31.229, 4.667],
                    [-26, 12.5],
                    [-14.677, 12.281],
                    [-3, 14],
                    [4, 3],
                    [5, -11],
                    [7.5, 1],
                    [20, -4.5],
                    [4.5, -1],
                    [13, 2],
                    [0, 0],
                    [-2, -3],
                    [-23.336, -7.326],
                  ],
                  v: [
                    [3132.5, 1354],
                    [3078.5, 1362.5],
                    [3032, 1390],
                    [2996, 1449],
                    [3001.5, 1509],
                    [3023.5, 1485.5],
                    [3064.5, 1469.5],
                    [3114, 1475],
                    [3164.501, 1448.5],
                    [3213.5, 1463],
                    [3237.5, 1450],
                    [3239.5, 1407.5],
                    [3195, 1370],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 2',
            },
          ],
          ef: [
            {
              ty: 34,
              nm: 'Puppet',
              np: 6,
              mn: 'ADBE FreePin3',
              ix: 1,
              en: 1,
              ef: [
                { ty: 7, nm: 'Puppet Engine', mn: 'ADBE FreePin3 Puppet Engine', ix: 1, v: { a: 0, k: 2, ix: 1 } },
                { ty: 0, nm: 'Mesh Rotation Refinement', mn: 'ADBE FreePin3 Auto Rotate Pins', ix: 2, v: { a: 0, k: 20, ix: 2 } },
                { ty: 7, nm: 'On Transparent', mn: 'ADBE FreePin3 On Transparent', ix: 3, v: { a: 0, k: 0, ix: 3 } },
                {
                  ty: '',
                  nm: 'arap',
                  np: 3,
                  mn: 'ADBE FreePin3 ARAP Group',
                  ix: 4,
                  en: 1,
                  ef: [
                    { ty: 6, nm: 'Auto-traced Shapes', mn: 'ADBE FreePin3 Outlines', ix: 1, v: 0 },
                    {
                      ty: '',
                      nm: 'Mesh',
                      np: 2,
                      mn: 'ADBE FreePin3 Mesh Group',
                      ix: 2,
                      en: 1,
                      ef: [
                        {
                          ty: '',
                          nm: 'Mesh 1',
                          np: 8,
                          mn: 'ADBE FreePin3 Mesh Atom',
                          ix: 1,
                          en: 1,
                          ef: [
                            { ty: 6, nm: 'Mesh', mn: 'ADBE FreePin3 Mesh', ix: 1, v: 0 },
                            { ty: 0, nm: 'Triangles', mn: 'ADBE FreePin3 Mesh Tri Count', ix: 2, v: { a: 0, k: 50, ix: 2 } },
                            { ty: 0, nm: 'Density', mn: 'ADBE FreePin3 Mesh Tri Density', ix: 3, v: { a: 0, k: 10, ix: 3 } },
                            { ty: 0, nm: 'Expansion', mn: 'ADBE FreePin3 Mesh Expansion', ix: 4, v: { a: 0, k: 3, ix: 4 } },
                            {
                              ty: '',
                              nm: 'Deform',
                              np: 9,
                              mn: 'ADBE FreePin3 PosPins',
                              ix: 5,
                              en: 1,
                              ef: [
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 8',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 1,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 27, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3220.5, 1370.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3219.5, 1392.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 7',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 2,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 28, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3109.5, 1322.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3106.5, 1361.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 6',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 3,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 29, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3010.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3011.5, 1429.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 5',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 4,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 30, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3050.5, 1473.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3050.5, 1464.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 4',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 5,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 31, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3177.5, 1446.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3176.5, 1436.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 3',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 6,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 32, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3233.5, 1409.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3230.5, 1440.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 2',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 7,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 33, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3106.5, 1428.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3113.5, 1432.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 1',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 8,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 34, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [2991.5, 1453.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3005.5, 1495.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                              ],
                            },
                            { ty: '', nm: 'Overlap', np: 1, mn: 'ADBE FreePin3 HghtPins', ix: 6, en: 1, ef: [] },
                            { ty: '', nm: 'Stiffness', np: 1, mn: 'ADBE FreePin3 StarchPins', ix: 7, en: 1, ef: [] },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 3,
          ty: 2,
          nm: 'R Eye',
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: {
              a: 1,
              k: [
                { i: { x: 0.667, y: 0.667 }, o: { x: 0.333, y: 0.333 }, t: 0, s: [3312, 3578, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                { i: { x: 0.667, y: 0.912 }, o: { x: 0.333, y: 0 }, t: 119, s: [3312, 3578, 0], to: [0, 0, 0], ti: [0, 0, 0] },
                {
                  i: { x: 0.667, y: 1 },
                  o: { x: 0.333, y: 0.098 },
                  t: 137,
                  s: [3312, 3621.583, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                {
                  i: { x: 0.667, y: 0.667 },
                  o: { x: 0.333, y: 0.333 },
                  t: 157,
                  s: [3312, 3578, 0],
                  to: [0, 0, 0],
                  ti: [0, 0, 0],
                },
                { t: 300, s: [3312, 3578, 0] },
              ],
              ix: 2,
              l: 2,
              x: 'var $bm_rt;\n$bm_rt = loopOut();',
            },
            a: { a: 0, k: [3136.5, 3388.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [30, -4.484],
                    [26, -12.5],
                    [19.5, -16.318],
                    [3, -14],
                    [-4, -3],
                    [-5, 11],
                    [-7.5, -1],
                    [-20, 4.5],
                    [-4.5, 1],
                    [-13, -2],
                    [0, 0],
                    [2, 3],
                    [33.5, 10.516],
                  ],
                  o: [
                    [-31.229, 4.667],
                    [-26, 12.5],
                    [-14.677, 12.281],
                    [-3, 14],
                    [4, 3],
                    [5, -11],
                    [7.5, 1],
                    [20, -4.5],
                    [4.5, -1],
                    [13, 2],
                    [0, 0],
                    [-2, -3],
                    [-23.336, -7.326],
                  ],
                  v: [
                    [3132.5, 1354],
                    [3078.5, 1362.5],
                    [3032, 1390],
                    [2996, 1449],
                    [3001.5, 1509],
                    [3023.5, 1485.5],
                    [3064.5, 1469.5],
                    [3114, 1475],
                    [3164.501, 1448.5],
                    [3213.5, 1463],
                    [3237.5, 1450],
                    [3239.5, 1407.5],
                    [3195, 1370],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 2',
            },
          ],
          ef: [
            {
              ty: 34,
              nm: 'Puppet',
              np: 6,
              mn: 'ADBE FreePin3',
              ix: 1,
              en: 1,
              ef: [
                { ty: 7, nm: 'Puppet Engine', mn: 'ADBE FreePin3 Puppet Engine', ix: 1, v: { a: 0, k: 2, ix: 1 } },
                { ty: 0, nm: 'Mesh Rotation Refinement', mn: 'ADBE FreePin3 Auto Rotate Pins', ix: 2, v: { a: 0, k: 20, ix: 2 } },
                { ty: 7, nm: 'On Transparent', mn: 'ADBE FreePin3 On Transparent', ix: 3, v: { a: 0, k: 0, ix: 3 } },
                {
                  ty: '',
                  nm: 'arap',
                  np: 3,
                  mn: 'ADBE FreePin3 ARAP Group',
                  ix: 4,
                  en: 1,
                  ef: [
                    { ty: 6, nm: 'Auto-traced Shapes', mn: 'ADBE FreePin3 Outlines', ix: 1, v: 0 },
                    {
                      ty: '',
                      nm: 'Mesh',
                      np: 2,
                      mn: 'ADBE FreePin3 Mesh Group',
                      ix: 2,
                      en: 1,
                      ef: [
                        {
                          ty: '',
                          nm: 'Mesh 1',
                          np: 8,
                          mn: 'ADBE FreePin3 Mesh Atom',
                          ix: 1,
                          en: 1,
                          ef: [
                            { ty: 6, nm: 'Mesh', mn: 'ADBE FreePin3 Mesh', ix: 1, v: 0 },
                            { ty: 0, nm: 'Triangles', mn: 'ADBE FreePin3 Mesh Tri Count', ix: 2, v: { a: 0, k: 50, ix: 2 } },
                            { ty: 0, nm: 'Density', mn: 'ADBE FreePin3 Mesh Tri Density', ix: 3, v: { a: 0, k: 10, ix: 3 } },
                            { ty: 0, nm: 'Expansion', mn: 'ADBE FreePin3 Mesh Expansion', ix: 4, v: { a: 0, k: 3, ix: 4 } },
                            {
                              ty: '',
                              nm: 'Deform',
                              np: 9,
                              mn: 'ADBE FreePin3 PosPins',
                              ix: 5,
                              en: 1,
                              ef: [
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 8',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 1,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 27, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3220.5, 1370.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3219.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3219.5, 1392.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 7',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 2,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 28, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3109.5, 1322.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3106.5, 1361.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3106.5, 1361.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 6',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 3,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 29, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3010.5, 1392.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3011.5, 1429.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3011.5, 1429.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 5',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 4,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 30, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3050.5, 1473.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3050.5, 1464.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3050.5, 1464.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 4',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 5,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 31, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3177.5, 1446.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3176.5, 1436.5],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3176.5, 1436.5] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 3',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 6,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 32, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3233.5, 1409.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3230.5, 1440.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3230.5, 1440.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 2',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 7,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 33, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [3106.5, 1428.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3113.5, 1432.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3113.5, 1432.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                                {
                                  ty: '',
                                  nm: 'Puppet Pin 1',
                                  np: 7,
                                  mn: 'ADBE FreePin3 PosPin Atom',
                                  ix: 8,
                                  en: 1,
                                  ef: [
                                    {
                                      ty: 3,
                                      nm: 'Vertex Offset',
                                      mn: 'ADBE FreePin3 PosPin Vtx Offset',
                                      ix: 1,
                                      v: { a: 0, k: [0, 0], ix: 1 },
                                    },
                                    {
                                      ty: 0,
                                      nm: 'Vertex Index',
                                      mn: 'ADBE FreePin3 PosPin Vtx Index',
                                      ix: 2,
                                      v: { a: 0, k: 34, ix: 2 },
                                    },
                                    { ty: 7, nm: 'Pin Type', mn: 'ADBE FreePin3 PosPin Type', ix: 3, v: { a: 0, k: 1, ix: 3 } },
                                    {
                                      ty: 3,
                                      nm: 'Position',
                                      mn: 'ADBE FreePin3 PosPin Position',
                                      ix: 4,
                                      v: {
                                        a: 1,
                                        k: [
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 0,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 119,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 1 },
                                            o: { x: 0.333, y: 0 },
                                            t: 138,
                                            s: [2991.5, 1453.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          {
                                            i: { x: 0.667, y: 0.667 },
                                            o: { x: 0.333, y: 0.333 },
                                            t: 157,
                                            s: [3005.5, 1495.808],
                                            to: [0, 0],
                                            ti: [0, 0],
                                          },
                                          { t: 300, s: [3005.5, 1495.808] },
                                        ],
                                        ix: 4,
                                        x: 'var $bm_rt;\n$bm_rt = loopOut();',
                                      },
                                    },
                                    { ty: 0, nm: 'Scale', mn: 'ADBE FreePin3 PosPin Scale', ix: 5, v: { a: 0, k: 100, ix: 5 } },
                                    { ty: 0, nm: 'Rotation', mn: 'ADBE FreePin3 PosPin Rotation', ix: 6, v: { a: 0, k: 0, ix: 6 } },
                                  ],
                                },
                              ],
                            },
                            { ty: '', nm: 'Overlap', np: 1, mn: 'ADBE FreePin3 HghtPins', ix: 6, en: 1, ef: [] },
                            { ty: '', nm: 'Stiffness', np: 1, mn: 'ADBE FreePin3 StarchPins', ix: 7, en: 1, ef: [] },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 4,
          ty: 2,
          nm: 'Man /Eka_005.psd',
          cl: 'psd',
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [3312, 3578, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3136.5, 3388.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: true,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [12, -6],
                    [0, 0],
                    [0, 0],
                    [99, -249],
                    [150, -24],
                    [-3, 9],
                    [99, -21],
                    [75.001, -33],
                    [0, 0],
                    [92, -6],
                    [62, 0],
                    [148, 24],
                    [150, 56],
                    [120, 2],
                    [50, -20],
                    [195, -69],
                    [90, 33],
                    [69, 102],
                    [-3, 30],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [-12, 6],
                    [0, 0],
                    [0, 0],
                    [-99, 249],
                    [-150, 24],
                    [-39, 27],
                    [-99, 21],
                    [-75.002, 33],
                    [0, 0],
                    [-92, 6],
                    [-62, 0],
                    [-148, -24],
                    [-150, -56],
                    [-120, -2],
                    [-50, 20],
                    [-195, 69],
                    [-90, -33],
                    [-69, -102],
                    [3, -30],
                    [0, 0],
                  ],
                  v: [
                    [-210, 5139],
                    [-435, 6960],
                    [6612, 6876],
                    [6432, 6456],
                    [6087, 5619],
                    [5772, 5715],
                    [5331, 6054],
                    [4710, 6099],
                    [4206, 6219],
                    [3977.999, 6318],
                    [3681, 6384],
                    [3512, 6396],
                    [3276, 6376],
                    [2986, 6354],
                    [2402, 6198],
                    [2050, 6158],
                    [1796, 6238],
                    [1551, 6357],
                    [921, 6306],
                    [507, 5979],
                    [462, 5796],
                    [474, 5400],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 5,
          ty: 2,
          nm: 'Man /Eka_005.psd',
          cl: 'psd',
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 0, ix: 10 },
            p: { a: 0, k: [3312, 3610, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3136.5, 3388.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [98, 98, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [12, -6],
                    [0, 0],
                    [0, 0],
                    [99, -249],
                    [150, -24],
                    [-3, 9],
                    [99, -21],
                    [75.001, -33],
                    [0, 0],
                    [92, -6],
                    [62, 0],
                    [148, 24],
                    [150, 56],
                    [120, 2],
                    [50, -20],
                    [195, -69],
                    [90, 33],
                    [69, 102],
                    [-3, 30],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [-12, 6],
                    [0, 0],
                    [0, 0],
                    [-99, 249],
                    [-150, 24],
                    [-39, 27],
                    [-99, 21],
                    [-75.002, 33],
                    [0, 0],
                    [-92, 6],
                    [-62, 0],
                    [-148, -24],
                    [-150, -56],
                    [-120, -2],
                    [-50, 20],
                    [-195, 69],
                    [-90, -33],
                    [-69, -102],
                    [3, -30],
                    [0, 0],
                  ],
                  v: [
                    [-210, 5139],
                    [-435, 6960],
                    [6612, 6876],
                    [6432, 6456],
                    [6087, 5619],
                    [5772, 5715],
                    [5331, 6054],
                    [4710, 6099],
                    [4206, 6219],
                    [3977.999, 6318],
                    [3681, 6384],
                    [3512, 6396],
                    [3276, 6376],
                    [2986, 6354],
                    [2402, 6198],
                    [2050, 6158],
                    [1796, 6238],
                    [1551, 6357],
                    [921, 6306],
                    [507, 5979],
                    [462, 5796],
                    [474, 5400],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ef: [
            {
              ty: 5,
              nm: 'Turbulent Displace',
              np: 16,
              mn: 'ADBE Turbulent Displace',
              ix: 1,
              en: 1,
              ef: [
                { ty: 7, nm: 'Displacement', mn: 'ADBE Turbulent Displace-0001', ix: 1, v: { a: 0, k: 1, ix: 1 } },
                { ty: 0, nm: 'Amount', mn: 'ADBE Turbulent Displace-0002', ix: 2, v: { a: 0, k: 25, ix: 2 } },
                { ty: 0, nm: 'Size', mn: 'ADBE Turbulent Displace-0003', ix: 3, v: { a: 0, k: 209, ix: 3 } },
                {
                  ty: 3,
                  nm: 'Offset (Turbulence)',
                  mn: 'ADBE Turbulent Displace-0004',
                  ix: 4,
                  v: { a: 0, k: [3136.5, 3388.5], ix: 4 },
                },
                { ty: 0, nm: 'Complexity', mn: 'ADBE Turbulent Displace-0005', ix: 5, v: { a: 0, k: 1, ix: 5 } },
                {
                  ty: 0,
                  nm: 'Evolution',
                  mn: 'ADBE Turbulent Displace-0006',
                  ix: 6,
                  v: {
                    a: 1,
                    k: [
                      { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [-360] },
                      { t: 300, s: [0] },
                    ],
                    ix: 6,
                    x: 'var $bm_rt;\n$bm_rt = loopOut();',
                  },
                },
                { ty: 6, nm: 'Evolution Options', mn: 'ADBE Turbulent Displace-0007', ix: 7, v: 0 },
                { ty: 7, nm: 'Cycle Evolution', mn: 'ADBE Turbulent Displace-0008', ix: 8, v: { a: 0, k: 1, ix: 8 } },
                { ty: 0, nm: 'Cycle (in Revolutions)', mn: 'ADBE Turbulent Displace-0009', ix: 9, v: { a: 0, k: 1, ix: 9 } },
                { ty: 0, nm: 'Random Seed', mn: 'ADBE Turbulent Displace-0010', ix: 10, v: { a: 0, k: 0, ix: 10 } },
                { ty: 6, nm: 'Random Seed', mn: 'ADBE Turbulent Displace-0011', ix: 11, v: 0 },
                { ty: 7, nm: 'Pinning', mn: 'ADBE Turbulent Displace-0012', ix: 12, v: { a: 0, k: 1, ix: 12 } },
                { ty: 7, nm: 'Resize Layer', mn: 'ADBE Turbulent Displace-0013', ix: 13, v: { a: 0, k: 0, ix: 13 } },
                { ty: 7, nm: 'Antialiasing for Best Quality', mn: 'ADBE Turbulent Displace-0014', ix: 14, v: { a: 0, k: 1, ix: 14 } },
              ],
            },
          ],
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
        {
          ddd: 0,
          ind: 6,
          ty: 2,
          nm: 'Man /Eka_005.psd',
          cl: 'psd',
          refId: 'image_0',
          sr: 1,
          ks: {
            o: { a: 0, k: 100, ix: 11 },
            r: { a: 0, k: 1, ix: 10 },
            p: { a: 0, k: [3416, 3850, 0], ix: 2, l: 2 },
            a: { a: 0, k: [3136.5, 3388.5, 0], ix: 1, l: 2 },
            s: { a: 0, k: [90, 90, 100], ix: 6, l: 2 },
          },
          ao: 0,
          hasMask: true,
          masksProperties: [
            {
              inv: false,
              mode: 'a',
              pt: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [0, 0],
                    [12, -6],
                    [0, 0],
                    [0, 0],
                    [99, -249],
                    [75.001, -33],
                    [0, 0],
                    [195, -69],
                    [-3, 30],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [0, 0],
                    [-12, 6],
                    [0, 0],
                    [0, 0],
                    [-99, 249],
                    [-75.002, 33],
                    [0, 0],
                    [-195, 69],
                    [3, -30],
                    [0, 0],
                  ],
                  v: [
                    [-210, 5139],
                    [-435, 6960],
                    [6612, 6876],
                    [6432, 6456],
                    [6087, 5619],
                    [5772, 5715],
                    [4155.776, 5580.223],
                    [3663.223, 5557.335],
                    [2448.778, 5254.778],
                    [1075.334, 5236.002],
                    [474, 5400],
                  ],
                  c: true,
                },
                ix: 1,
              },
              o: { a: 0, k: 100, ix: 3 },
              x: { a: 0, k: 0, ix: 4 },
              nm: 'Mask 1',
            },
          ],
          ip: 0,
          op: 901,
          st: 0,
          bm: 0,
        },
      ],
    },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 0,
      nm: 'Man ',
      refId: 'comp_0',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [3218.5, 4659.5, 0], ix: 2, l: 2 },
        a: { a: 0, k: [3312, 3578, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      w: 6624,
      h: 7156,
      ip: 0,
      op: 901,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 2,
      nm: 'Green circle',
      refId: 'image_1',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            { i: { x: [0.833], y: [0.833] }, o: { x: [0.167], y: [0.167] }, t: 0, s: [-360] },
            { t: 601, s: [0] },
          ],
          ix: 10,
          x: 'var $bm_rt;\n$bm_rt = loopOut();',
        },
        p: { a: 0, k: [2999.5, 2382.5, 0], ix: 2, l: 2 },
        a: { a: 0, k: [1620.5, 1635.5, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      ip: 0,
      op: 901,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 2,
      nm: 'Layer 2',
      refId: 'image_2',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [3118, 4250, 0], ix: 2, l: 2 },
        a: { a: 0, k: [2755, 1960, 0], ix: 1, l: 2 },
        s: {
          a: 1,
          k: [
            { i: { x: [0.205, 0.205, 0.667], y: [1, 1, 1] }, o: { x: [0.333, 0.333, 0.333], y: [0, 0, 0] }, t: 0, s: [97, 97, 100] },
            { i: { x: [0.667, 0.667, 0.667], y: [1, 1, 1] }, o: { x: [0.745, 0.745, 0.333], y: [0, 0, 0] }, t: 35, s: [95, 95, 100] },
            { t: 60, s: [97, 97, 100] },
          ],
          ix: 6,
          l: 2,
          x: 'var $bm_rt;\n$bm_rt = loopOut();',
        },
      },
      ao: 0,
      ip: 0,
      op: 901,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
